spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/drowsiness_detection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
email.password = ukio extq fgyo pfrk

encryption.key = My16CharKey12345
spring.mail.host=smtp.gmail.com
spring.mail.port=587